"""Verify command strings generated by the driver match the TDS2024C manual.

All tests use a mock VISA instrument so no hardware is required.
"""

import pytest
from unittest.mock import MagicMock, patch, call


def _make_osc(resource="USB0::0x0699::0x03A6::TEST::INSTR"):
    """Return a TDS2024C with a mocked VISA session."""
    from tektronix_tds2024c import TDS2024C
    osc = TDS2024C(resource)
    inst = MagicMock()
    inst.query.return_value = "0"
    inst.read_raw.return_value = b"#14\x00\x01\x02\x03"
    osc._inst = inst
    osc._rm   = MagicMock()
    return osc, inst


# ── Acquisition ────────────────────────────────────────────────────────────────

def test_acq_mode_sample():
    from tektronix_tds2024c import AcqMode
    osc, inst = _make_osc()
    osc.set_acq_mode(AcqMode.SAMPLE)
    inst.write.assert_called_with("ACQuire:MODe SAMple")


def test_acq_mode_average():
    from tektronix_tds2024c import AcqMode
    osc, inst = _make_osc()
    osc.set_acq_mode(AcqMode.AVERAGE)
    inst.write.assert_called_with("ACQuire:MODe AVErage")


def test_acq_numavg():
    osc, inst = _make_osc()
    osc.set_acq_numavg(16)
    inst.write.assert_called_with("ACQuire:NUMAVg 16")


def test_acq_single_sends_two_commands():
    osc, inst = _make_osc()
    osc.acq_single()
    calls = [c[0][0] for c in inst.write.call_args_list]
    assert "ACQuire:STOPAfter SEQuence" in calls
    assert "ACQuire:STATE RUN" in calls


def test_acq_stop():
    osc, inst = _make_osc()
    osc.acq_stop()
    inst.write.assert_called_with("ACQuire:STATE STOP")


# ── Vertical ───────────────────────────────────────────────────────────────────

def test_channel_scale_ch1():
    from tektronix_tds2024c import Channel
    osc, inst = _make_osc()
    osc.set_channel_scale(Channel.CH1, 0.5)
    written = inst.write.call_args[0][0]
    assert written.startswith("CH1:SCAle")
    assert "5" in written  # 0.5 formatted as scientific


def test_channel_scale_ch3():
    from tektronix_tds2024c import Channel
    osc, inst = _make_osc()
    osc.set_channel_scale(Channel.CH3, 0.1)
    written = inst.write.call_args[0][0]
    assert written.startswith("CH3:SCAle")


def test_channel_coupling_dc():
    from tektronix_tds2024c import Channel, Coupling
    osc, inst = _make_osc()
    osc.set_channel_coupling(Channel.CH2, Coupling.DC)
    inst.write.assert_called_with("CH2:COUPling DC")


def test_channel_coupling_ac():
    from tektronix_tds2024c import Channel, Coupling
    osc, inst = _make_osc()
    osc.set_channel_coupling(Channel.CH2, Coupling.AC)
    inst.write.assert_called_with("CH2:COUPling AC")


def test_channel_bw_limit_full():
    from tektronix_tds2024c import Channel, BandwidthLimit
    osc, inst = _make_osc()
    osc.set_channel_bw_limit(Channel.CH1, BandwidthLimit.FULL)
    inst.write.assert_called_with("CH1:BANdwidth ON")


def test_channel_display_on():
    from tektronix_tds2024c import Channel
    osc, inst = _make_osc()
    osc.set_channel_display(Channel.CH4, True)
    inst.write.assert_called_with("SELect:CH4 ON")


def test_channel_display_off():
    from tektronix_tds2024c import Channel
    osc, inst = _make_osc()
    osc.set_channel_display(Channel.CH4, False)
    inst.write.assert_called_with("SELect:CH4 OFF")


def test_channel_probe():
    from tektronix_tds2024c import Channel
    osc, inst = _make_osc()
    osc.set_channel_probe(Channel.CH1, 10.0)
    inst.write.assert_called_with("CH1:PROBe 10")


# ── Horizontal ─────────────────────────────────────────────────────────────────

def test_time_scale():
    osc, inst = _make_osc()
    osc.set_time_scale(1e-4)
    written = inst.write.call_args[0][0]
    assert written.startswith("HORizontal:MAIn:SCAle")
    assert "E" in written.upper()


# ── Trigger ────────────────────────────────────────────────────────────────────

def test_trigger_type_edge():
    from tektronix_tds2024c import TriggerType
    osc, inst = _make_osc()
    osc.set_trigger_type(TriggerType.EDGE)
    inst.write.assert_called_with("TRIGger:MAIn:TYPe EDGE")


def test_trigger_source_ch1():
    from tektronix_tds2024c import Channel
    osc, inst = _make_osc()
    osc.set_trigger_source(Channel.CH1)
    inst.write.assert_called_with("TRIGger:MAIn:EDGE:SOUrce CH1")


def test_trigger_level():
    osc, inst = _make_osc()
    osc.set_trigger_level(0.0)
    written = inst.write.call_args[0][0]
    assert written.startswith("TRIGger:MAIn:LEVel")


def test_trigger_slope_rise():
    from tektronix_tds2024c import TriggerSlope
    osc, inst = _make_osc()
    osc.set_trigger_slope(TriggerSlope.RISE)
    inst.write.assert_called_with("TRIGger:MAIn:EDGE:SLOpe RISe")


def test_trigger_slope_fall():
    from tektronix_tds2024c import TriggerSlope
    osc, inst = _make_osc()
    osc.set_trigger_slope(TriggerSlope.FALL)
    inst.write.assert_called_with("TRIGger:MAIn:EDGE:SLOpe FALL")


def test_force_trigger():
    osc, inst = _make_osc()
    osc.force_trigger()
    inst.write.assert_called_with("TRIGger FORCe")


# ── Measurement ────────────────────────────────────────────────────────────────

def test_immed_source():
    from tektronix_tds2024c import Channel
    osc, inst = _make_osc()
    osc.set_immed_source(Channel.CH2)
    inst.write.assert_called_with("MEASUrement:IMMed:SOUrce1 CH2")


def test_immed_type_frequency():
    from tektronix_tds2024c import MeasType
    osc, inst = _make_osc()
    osc.set_immed_type(MeasType.FREQUENCY)
    inst.write.assert_called_with("MEASUrement:IMMed:TYPe FREQuency")


def test_immed_type_rms():
    from tektronix_tds2024c import MeasType
    osc, inst = _make_osc()
    osc.set_immed_type(MeasType.RMS)
    inst.write.assert_called_with("MEASUrement:IMMed:TYPe RMS")


def test_measure_no_value_raises():
    from tektronix_tds2024c import Channel, MeasType, TDS2024CMeasurementError, MEAS_NO_VALUE
    osc, inst = _make_osc()
    inst.query.return_value = str(MEAS_NO_VALUE)
    with pytest.raises(TDS2024CMeasurementError):
        osc.measure(Channel.CH1, MeasType.FREQUENCY)


# ── Waveform ───────────────────────────────────────────────────────────────────

def test_waveform_source_command():
    from tektronix_tds2024c import Channel
    osc, inst = _make_osc()
    osc.set_waveform_source(Channel.CH1)
    inst.write.assert_called_with("DATa:SOUrce CH1")


def test_waveform_encoding_ribinary():
    from tektronix_tds2024c import WfmEncoding
    osc, inst = _make_osc()
    osc.set_waveform_encoding(WfmEncoding.RIBINARY)
    inst.write.assert_called_with("DATa:ENCdg RIBinary")


def test_waveform_width_1():
    from tektronix_tds2024c import WfmWidth
    osc, inst = _make_osc()
    osc.set_waveform_width(WfmWidth.ONE_BYTE)
    inst.write.assert_called_with("DATa:WIDth 1")


def test_waveform_start_stop():
    osc, inst = _make_osc()
    osc.set_waveform_start(1)
    osc.set_waveform_stop(2500)
    calls = [c[0][0] for c in inst.write.call_args_list]
    assert "DATa:STARt 1" in calls
    assert "DATa:STOP 2500" in calls


# ── Misc ───────────────────────────────────────────────────────────────────────

def test_header_off():
    osc, inst = _make_osc()
    osc.set_header(False)
    inst.write.assert_called_with("HEADer OFF")


def test_lock_front_panel():
    osc, inst = _make_osc()
    osc.lock_front_panel()
    inst.write.assert_called_with("LOCk ALL")


def test_unlock_front_panel():
    osc, inst = _make_osc()
    osc.unlock_front_panel()
    inst.write.assert_called_with("UNLock ALL")


def test_autoset_sends_execute():
    osc, inst = _make_osc()
    inst.query.return_value = "1"  # *OPC? → 1
    osc.autoset()
    calls = [c[0][0] for c in inst.write.call_args_list]
    assert "AUTOSet EXECUTE" in calls


# ── Getter parsing against realistic (uppercase) device responses ───────────────

def test_get_acq_mode_parses_uppercase():
    from tektronix_tds2024c import AcqMode
    osc, inst = _make_osc()
    inst.query.return_value = "AVERAGE"
    assert osc.get_acq_mode() is AcqMode.AVERAGE


def test_get_trigger_slope_parses_uppercase():
    from tektronix_tds2024c import TriggerSlope
    osc, inst = _make_osc()
    inst.query.return_value = "FALL"
    assert osc.get_trigger_slope() is TriggerSlope.FALL


def test_get_trigger_source_parses_line():
    from tektronix_tds2024c import TriggerSource
    osc, inst = _make_osc()
    inst.query.return_value = "LINE"
    assert osc.get_trigger_source() is TriggerSource.LINE


def test_get_trigger_coupling_parses_noiserej():
    from tektronix_tds2024c import TriggerCoupling
    osc, inst = _make_osc()
    inst.query.return_value = "NOISEREJ"
    assert osc.get_trigger_coupling() is TriggerCoupling.NOISE_REJ


def test_get_channel_coupling_parses():
    from tektronix_tds2024c import Channel, Coupling
    osc, inst = _make_osc()
    inst.query.return_value = "GND"
    assert osc.get_channel_coupling(Channel.CH1) is Coupling.GND


def test_get_immed_units_strips_quotes():
    osc, inst = _make_osc()
    inst.query.return_value = '"Hz"'
    assert osc.get_immed_units() == "Hz"


def test_get_channel_display_true():
    from tektronix_tds2024c import Channel
    osc, inst = _make_osc()
    inst.query.return_value = "1"
    assert osc.get_channel_display(Channel.CH1) is True


def test_set_trigger_source_accepts_ext():
    from tektronix_tds2024c import TriggerSource
    osc, inst = _make_osc()
    osc.set_trigger_source(TriggerSource.EXT)
    inst.write.assert_called_with("TRIGger:MAIn:EDGE:SOUrce EXT")


# ── capture_waveform with mocked binary transfer + positional WFMPre ────────────

def test_capture_waveform_binary_decodes_scaling():
    from tektronix_tds2024c import Channel, WfmEncoding
    osc, inst = _make_osc()
    # Realistic header-off positional WFMPre? response (16 fields)
    wfmpre = ('1;8;BIN;RI;MSB;5;"Ch1";Y;1.0E-9;0;0.0E0;"s";'
              '5.0E-1;0.0E0;0.0E0;"Volts"')
    inst.query.return_value = wfmpre
    import numpy as np
    inst.query_binary_values.return_value = np.array([0, 2, -2, 10, -10], dtype=np.int8)

    rec = osc.capture_waveform(Channel.CH1, encoding=WfmEncoding.RIBINARY, stop=5)

    # query_binary_values must be called with signed-byte, big-endian
    _, kwargs = inst.query_binary_values.call_args
    assert kwargs["datatype"] == "b"
    assert kwargs["is_big_endian"] is True
    # v = (adc - yoff) * ymult + yzero = adc * 0.5
    np.testing.assert_array_almost_equal(rec.v, [0.0, 1.0, -1.0, 5.0, -5.0])
    assert rec.dt == 1e-9
    assert rec.preamble.y_unit == "Volts"
